name: CI
on:
  pull_request:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: adopt
            jobtype: 7
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    env:
      JAVA_OPTS: -Xms800M -Xmx2G -Xss6M -XX:ReservedCodeCacheSize=128M -server -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms800M -Xmx2G -Xss6M -XX:ReservedCodeCacheSize=128M -server -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      SCALA_212: 2.12.20
      UTIL_TESTS: "utilCache/test utilControl/test utilInterface/test utilLogging/test utilPosition/test utilRelation/test utilScripted/test utilTracking/test"
      TEST_SBT_VER: 1.10.4
      SBT_ETC_FILE: $HOME/etc/sbt/sbtopts
      JDK11: adopt@1.11.0-9
      SPARK_LOCAL_IP: "127.0.0.1"
    steps:
    - name: Checkout sbt/sbt
      uses: actions/checkout@v4
    - name: Checkout sbt/io
      uses: actions/checkout@v4
      with:
        repository: sbt/io
        ref: develop
        path: io
    - name: Checkout sbt/librarymanagement
      uses: actions/checkout@v4
      with:
        repository: sbt/librarymanagement
        ref: develop
        path: librarymanagement
    - name: Checkout sbt/zinc
      uses: actions/checkout@v4
      with:
        repository: sbt/zinc
        ref: 1.10.x
        path: zinc
    - uses: graalvm/setup-graalvm@v1
      if: ${{ matrix.jobtype >= 7 && matrix.jobtype <= 9 }}
      with:
        java-version: '23'
        native-image-musl: 'true'
        set-java-home: 'false'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Coursier cache
      uses: coursier/cache-action@v6
    - name: Cache sbt
      uses: actions/cache@v4
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - name: Build and test (7)
      if: ${{ matrix.jobtype == 7 }}
      shell: bash
      run: |
        # test building sbtn on Linux
        sbt "-Dsbt.io.virtual=false" nativeImage
    - name: Upload sbtn native image
      if: ${{ matrix.jobtype == 7 }}
      uses: actions/upload-artifact@v3
      with:
        name: sbtn-native-image
        path: bin/sbtn
    - name: Cleanup
      shell: bash
      run: |
        rm -rf "$HOME/.sbt/scripted/" || true
        rm -rf "$HOME/.ivy2/local" || true
        rm -r $(find $HOME/.sbt/boot -name "*-SNAPSHOT") || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
